services:
  - type: web
    name: hashweb-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://https-github-com-codechamp12345-has.vercel.app
      - key: COOKIE_DOMAIN
        sync: false
      - key: PORT
        value: 10000 